on:
  fork:
  push:
    branches: [main]
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened]
  pull_request_review_comment:
    types: [created]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: run env
        run: echo ${{ secrets.GENERAL_TOKEN }}
      - name: run env2
        run: echo $GENERAL_TOKEN
      - uses: actions/checkout@main
      - uses: EddieHubCommunity/gh-action-community/src/welcome@main
        with:
          github-token: ${{ secrets.GENERAL_TOKEN}}
          issue-message: |
            ## Thanks for taking the time to contribute by creating an issue
            #### It's great having you!.
            This is an automated message,you'll get a response from a maintainer soon.
          pr-message: |
            ## Thanks for taking the time to contribute by creating a pull request.
            Please hold on while your contributions are being reviewed.
            This is an automated message,you'll get a response from a maintainer soon.
